# -*- coding: utf-8 -*-
"""LoadData.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HBv8q212sw3sqmToqJ7MICfd9LMxoAow
"""

import os
import glob
import cv2
import matplotlib.pyplot as plt
import numpy as np


def load_masd_data():
    root_gt = "/Documents/MASD Segmentation/Datasets/MASD_GT"
    root_ori = "/Documents/MASD Segmentation/Datasets/MASD_O"
    images_gt = []
    images_ori = []
    files_gt=[]
    files_ori=[]
    
    dirlist_gt = os.listdir(root_gt)
    print(dirlist_gt)
    dirlist_ori = os.listdir(root_ori)
    for (gt_folder,ori_folder) in zip(dirlist_gt,dirlist_ori):
        if gt_folder != ".DS_Store" and ori_folder != ".DS_Store":
            path_gt = root_gt+"/"+str(gt_folder)
            print(path_gt)
            path_ori = root_ori+"/"+str(ori_folder)
            file_list_gt = os.listdir(path_gt)
            file_list_ori = os.listdir(path_ori)
            print(file_list_gt)
            for (gt_folder,ori_folder) in zip(file_list_gt,file_list_ori):
                file_path_gt = path_gt+"/"+str(gt_folder)
                print(file_path_gt)
                file_path_ori = path_ori+"/"+str(ori_folder)
                files_gt.append(file_path_gt)
                files_ori.append(file_path_ori)
               
                image_gt = cv2.resize(cv2.imread(file_path_gt,cv2.IMREAD_GRAYSCALE),(256,256))
                images_gt.append(image_gt)
                #plt.imshow(image_gt)
                #plt.show()
                
                image_ori = cv2.resize(cv2.imread(file_path_ori,cv2.IMREAD_GRAYSCALE),(256,256))
                images_ori.append(image_ori)
                #plt.imshow(image_ori)
                #plt.show()
              
    return images_ori,images_gt

def load_msd_data():
    root_gt = "/Documents/MASD Segmentation/Datasets/MSD_GT"
    root_ori = "/Documents/MASD Segmentation/Datasets/MSD_O"
    images_gt = []
    images_ori = []
    files_gt=[]
    files_ori=[]
    
    dirlist_gt = os.listdir(root_gt)
    print(dirlist_gt)
    dirlist_ori = os.listdir(root_ori)
    for (gt_folder,ori_folder) in zip(dirlist_gt,dirlist_ori):
        if gt_folder != ".DS_Store" and ori_folder != ".DS_Store":
            path_gt = root_gt+"/"+str(gt_folder)
            print(path_gt)
            path_ori = root_ori+"/"+str(ori_folder)
            file_list_gt = os.listdir(path_gt)
            file_list_ori = os.listdir(path_ori)
            print(file_list_gt)
            for (gt_folder,ori_folder) in zip(file_list_gt,file_list_ori):
                file_path_gt = path_gt+"/"+str(gt_folder)
                print(file_path_gt)
                file_path_ori = path_ori+"/"+str(ori_folder)
                files_gt.append(file_path_gt)
                files_ori.append(file_path_ori)
               
                image_gt = cv2.resize(cv2.imread(file_path_gt,cv2.IMREAD_GRAYSCALE),(256,256))
                images_gt.append(image_gt)
                #plt.imshow(image_gt)
                #plt.show()
                
                image_ori = cv2.resize(cv2.imread(file_path_ori,cv2.IMREAD_GRAYSCALE),(256,256))
                images_ori.append(image_ori)
                #plt.imshow(image_ori)
                #plt.show()
              
    return images_ori,images_gt
    
    
images_masd,images_masd_gt = load_masd_data()

images_msd,images_msd_gt = load_msd_data()

X=[]
y=[]

for imgs in range(len(images_masd)):
    X.append(images_masd[imgs])
    y.append(images_masd_gt[imgs])
    
for imgs in range(len(images_msd)):
    X.append(images_msd[imgs])
    y.append(images_msd_gt[imgs])
    
X = np.array(X)
y = np.array(y)

np.save("/Documents/MASD Segmentation/Datasets/X_256.npy",X)
np.save("/Documents/MASD Segmentation/Datasets/y_256.npy",y)